{'name': 'Odoo Cancel Manufacture Order',
'summary': 'Easily cancel the processed Manufacture order' ,
'sequence': 1,
'description': 'Easily cancel the processed sale order ',
'images': ['static/description/Banner.png'],
'category': 'stock',
'version': '15.0.0.1',
'author': 'Keypress IT Services',
'website': 'https://www.keypress.co.in',
'depends': ['mrp', 'cancel_stock_picking_spt'],
'data': ['views/mrp_production_view.xml'],
'application': True,
'installable': True,
'auto_install': False,
}