{'name': 'Odoo Cancel Delivery',
'summary': 'Easily cancel delivery orders in odoo and get all your stock return in the warehouse via a single click, cancel multiple delivery orders.\nOdoo cancel delivery, odoo cancel delivery order, odoo cancel picking, odoo return stock, odoo cancel processed order, odoo cancel sale',
'sequence': 1,
'description': 'Easily cancel delivery orders in odoo and get all your stock return in the warehouse via a single click, cancel multiple delivery orders.\nOdoo cancel delivery, odoo cancel delivery order, odoo cancel picking, odoo return stock, odoo cancel processed order, odoo cancel sale',
'images': ['static/description/Banner.png'],
'currency': 'USD',
'category': 'stock',
'version': '15.0.0.3',
'author': 'Keypress IT Services',
'website': 'https://www.keypress.co.in',
'depends': ['stock', 'account'],
'data': ['security/cancel_picking_rule_spt.xml','data/ir_actions_server_spt.xml', 'views/stock_picking_view.xml'],
'application': True,
'installable': True,
'auto_install': False,
'live_test_url': 'https://youtu.be/otYsdupKi9s',}
